name: flutter_boilerplate
description: A simple boilerplate project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  auto_route: 3.0.3
  intl: ^0.17.0
  meta: ^1.7.0
  dio: ^4.0.0
  json_annotation: ^4.3.0
  pretty_dio_logger: ^1.1.1
  flutter_secure_storage: ^4.2.1
  google_fonts: ^2.1.0
  lottie: ^1.2.1
  connectivity_plus: ^2.0.2
  shared_preferences: ^2.0.8
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  very_good_analysis: ^2.4.0
  dart_code_metrics: ^4.4.0
  very_good_performance: ^0.0.4
  dependency_validator: ^3.1.0
  json_serializable:
  build_runner:
  flutter_gen_runner:
  freezed: ^0.15.0+1
  auto_route_generator: 3.0.1
  logger:
  import_sorter: ^4.6.0
  flutter_lints: ^1.0.4


## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/.env.production
    - assets/env/.env.staging
    - assets/env/.env.development
    - assets/env/
    - assets/
    - assets/image/
